### ISSUE TITLE
URL error

### ISSUE THREAD

**Issue by wessware** [WanjikuMutuku/alx-higher_level_programming#1]
`#!/usr/bin/python3
""" sends a request to the URL and displays the body of the response."""
import requests
import sys

if __name__ == "__main__":
    # Provide a valid URL as a command-line argument
    if len(sys.argv) > 1:
        url = sys.argv[1]
    else:
        url = "https://www.example.com/"  # Replace with your desired URL

    response = requests.get(url)

    if response.status_code >= 400:
        print("Error code:", response.status_code)
    else:
        print(response.text)`

@WanjikuMutuku - I did try your code on a web environment and I had a lot of trouble getting it simulate a practical fetch. I made a small update - I hope the sandbox accepts it.

**Comment by WanjikuKinyua** [comment]
That one was a mess... I tried to run it but it couldn't go through all
checks.
Thanks for going through it.
